name: rebuild-prebuilts

on:
#  schedule:
#    - cron: '0 10 * * *' # everyday at 10am
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      -
        name: Set Permissions
        id: set-permissions
        run: find . -type f -iname "*.sh" -exec chmod +x {} \;
        working-directory: dockerbuildsystem
      -
        name: Run build
        id: build-docker
        run: |
          bash ./build-docker.sh
          # check for output files
          DEPLOYFILECOUNT=$(ls -1 . | wc -l)
          if [ "$DEPLOYFILECOUNT" -ge 2 ]
          then
          echo "Done! Your image(s) should be in deploy/"
          exit 0
          else
          echo "The script failed" >&2
          exit 1
          fi
        working-directory: dockerbuildsystem
      - 
        name: Upload build artifacts 
        id: upload_deploy
        uses: actions/upload-artifact@v2
        with:
          name: deploy
          path: |
            ./dockerbuildsystem/pi-gen/deploy/*.info
            ./dockerbuildsystem/pi-gen/deploy/*.zip
            ./dockerbuildsystem/pi-gen/deploy/build.log
